[package]
name = "C24U_Server"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tls = "~0.3"
tokio-native-tls = "~0.3"
native-tls = "~0.2"
base64 = "~0.13.0"
env_logger = "~0.11"
log = "~0.4"